### ISSUE TITLE
Banner

### ISSUE THREAD

**Issue by kafiln** [kafiln/kafil.now.sh#11]
Add a thumbnail banner image to the readme file

**Comment by RivaD2** [comment]
I would be honored to work on this for you! Can you assign it to me?

**Comment by kafiln** [comment]
The honor would be mine !

**Comment by RivaD2** [comment]
Alright, we are on it. Thank you for your time!

**Comment by kafiln** [comment]
Thank you 👍🏾 
I also made a design in figma https://www.figma.com/file/jC240DYa9KguQTGgAsnmru/Blog?node-id=0%3A1
I'm kind of new to the design world.

**Comment by RivaD2** [comment]
Please let us know if you would like an actual banner :) We can also remove HTML markup as I know that can be a personal preference on Readme files. We added only the image to the page (no color or actual resizing). We are happy to hear any suggestions you have.

**Comment by RivaD2** [comment]
Also, I love Figma! I use it for white boarding visuals and wireframing. Your design is lovely!

**Comment by kafiln** [comment]
Thank you for you time and contribution.
I just starting using figma and I love it so far.
For the banner I was thinking of a preview of the website or maybe the hero section, the goal is the show what the website looks like for people that may be interesting in forking this repo to create their own website.

**Comment by RivaD2** [comment]
Of course, we are happy to help you with this issue! We removed the old thumbnail and just added a new thumbnail based off your Figma mock up. Please let us know if this is in line to what you were thinking :)

**Comment by kafiln** [comment]
Nice 👍🏾 
Thank you
